version: "3.8"
services:
  api:
    build:
      context: .
      args:
        NODE_ENV: production
    command: npm start

  nginx:
    volumes:
      - ./files/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./files/ssl/ca.pem:/etc/ssl/certs/cert.pem:ro
      - ./files/ssl/flare.crt:/etc/ssl/certs/cloudflare.crt:ro
      - ./files/ssl/priv.pem:/etc/ssl/private/key.pem:ro
    ports:
      - "80:80"
      - "443:443"