version: "3.8"
services:
  api:
    build:
      context: .
      args:
        NODE_ENV: development
    command: npm start

  nginx:
    volumes:
      - ./files/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"